In [27]:
# numpy >> numerical python
# 2005 by Travis Oliphant
# before 2005 there were special mathematical tools (similar to tora, linga)

In [28]:
import numpy as np  # as is alias

In [29]:
np.__version__

'2.2.4'

In [30]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [31]:
lis = [1, 2, 3, "lucky", 3+5j, True, 1.2]  # List stores heterogenous data
type(lis)

list

In [32]:
# numpy stored the data in a numpy array
# an array is a container/data structure used to store data of same data type >> homogenous data

In [ ]:
# why numpy? already we have list. >> C is one of the fastest programing language after C++
# numpy is built using C >> numpy computation is fast
# why numpy is fast >> due to array >> since it stores only homogenous data numpy array is faster
# since it stores homogenous data >> it has continuous/contiguous memory locations >> that's why mathematical computation is fast

In [34]:
l = [1, 2, 3, 4, 5]

In [35]:
np.array(l)

array([1, 2, 3, 4, 5])

In [36]:
arr = np.array(l)  # numpy.ndarray >> n dimensional array

In [37]:
type(arr)

numpy.ndarray

In [38]:
arr

array([1, 2, 3, 4, 5])

In [39]:
l = [1, 2, 3, 4, 5, "Lucky"]
np.array(l)

array(['1', '2', '3', '4', '5', 'Lucky'], dtype='<U21')

In [40]:
# array stores homogenous data

In [41]:
l = [1, 2, 3, 4, 5, 6.1]
np.array(l)

array([1. , 2. , 3. , 4. , 5. , 6.1])

In [42]:
arr

array([1, 2, 3, 4, 5])

In [43]:
arr.ndim  # arr has only raw

1

In [44]:
np.array([[1,2,3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr1 = np.array([[1,2,3],[4, 5, 6]])

In [46]:
arr1.ndim

2

In [47]:
np.matrix([1, 2, 3, 4]) # matrix is a specialised array of 2 dimension

matrix([[1, 2, 3, 4]])

In [48]:
mat = np.matrix([1, 2, 3, 4])

In [49]:
type(mat)

numpy.matrix

In [50]:
mat.ndim

2

In [51]:
# to understand the dimention, see the no of opening/closing square bracket

In [52]:
# np.matrix([[[1,2],[3,4],[5,6]]])  # will throw error - matrix must be 2-dimensional

In [53]:
arr3 = np.array([[[1,2],[3,4],[5,6]]])

In [54]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [55]:
# more way to array
l = [1, 2, 3]
np.asarray(l)  # initial function asarray to convert to an array, np.array came after this

array([1, 2, 3])

In [56]:
np.asanyarray([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# asanyarray will convert the input to an adarry, but if something as already in array it will not convert >> it will pass ndarray subclass throuth
# if somthingis already an array or part of array, it will simply allow to pass throuth it

In [58]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [59]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [60]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [61]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
for i in arr:
    print(i)

1
2
3
4
5


In [63]:
arr[0]

np.int64(1)

In [64]:
arr[3]

np.int64(4)

In [65]:
#array is mutable
arr[0] = 100

In [66]:
arr

array([100,   2,   3,   4,   5])

In [67]:
a = arr  # a and arr will point to same memory location, so if there is changes in a or both it will reflact in both

In [68]:
a

array([100,   2,   3,   4,   5])

In [69]:
arr

array([100,   2,   3,   4,   5])

In [70]:
# shallow copy >> change in one array will lead to chnage in another

In [71]:
a[1] = 200

In [72]:
a

array([100, 200,   3,   4,   5])

In [73]:
arr

array([100, 200,   3,   4,   5])

In [74]:
b = arr.copy() # deep copy >> change in one array will not replect in another

In [75]:
b

array([100, 200,   3,   4,   5])

In [76]:
b[2] = 3000

In [77]:
b

array([ 100,  200, 3000,    4,    5])

In [78]:
arr

array([100, 200,   3,   4,   5])

In [ ]:
# to create an array >> np.array, np.array, np.asanyarray

In [80]:
# multiple approches to generate any array

In [81]:
arr2 = np.fromfunction(lambda i, j: i==j, (3,3)) # construct an array by executing a function over each coorinate

In [82]:
arr2

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [83]:
arr2.ndim

2

In [84]:
arr2.shape # shape of array

(3, 3)

In [85]:
arr2.size  # no of element in array

9

In [86]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [87]:
for i in range(5):
    print(i)

0
1
2
3
4


In [88]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [89]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [90]:
iterator = (i for i in range(5))

In [91]:
iterator

<generator object <genexpr> at 0x000001FB9089BE80>

In [92]:
# np.formiter(iterator, int)  # create a new 1- dimentional array from an iterable object

In [93]:
np.fromstring('22 23 24', sep = " ")

array([22., 23., 24.])

In [94]:
# np.fromstring('22 23 24', sep = " ", dttype = int)

In [95]:
# for string character you have to use splite
string = "Lucky, Kushik, LalBabu"
string.split(" , ")

['Lucky, Kushik, LalBabu']

In [96]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [97]:
#other method of numpy >> to generate a sequence of number
np.arange

<function numpy.arange>