In [1]:
# numpy >> numerical python
# 2005 by Travis Oliphant
# before 2005 there were special mathematical tools (similar to tora, linga)

In [3]:
import numpy as np  # as is aloas

In [5]:
np.__version__

'1.26.4'

In [9]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [11]:
lis = [1, 2, 3, "lucky", 3+5j, True, 1.2]  # List stores heterogenous data
type(lis)

list

In [13]:
# numpy stored the data in a numpy array
# an array is a container/data structure used to store data of same data type >> homogenous data

In [15]:
# why numpy? already we have list. >> C is one of the fastest programing language after C++
# numpy is built using C >> numpy computation is fast
# why numpy is fast >> due to array >> since it stores only homogenous data numpy array is faster
# sice it stores homogenous data >> it has continuous/contiguous memory locations >> that's why mathematical computation is fast

In [17]:
l = [1, 2, 3, 4, 5]

In [19]:
np.array(l)

array([1, 2, 3, 4, 5])

In [21]:
arr = np.array(l)  # numpy.ndarray >> n dimensional array

In [23]:
type(arr)

numpy.ndarray

In [25]:
arr

array([1, 2, 3, 4, 5])

In [27]:
l = [1, 2, 3, 4, 5, "Lucky"]
np.array(l)

array(['1', '2', '3', '4', '5', 'Lucky'], dtype='<U11')

In [31]:
# array stores homogenous data

In [29]:
l = [1, 2, 3, 4, 5, 6.1]
np.array(l)

array([1. , 2. , 3. , 4. , 5. , 6.1])

In [35]:
arr

array([1, 2, 3, 4, 5])

In [39]:
arr.ndim  # arr has only raw

1

In [43]:
np.array([[1,2,3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr1 = np.array([[1,2,3],[4, 5, 6]])

In [49]:
arr1.ndim

2

In [51]:
np.matrix([1, 2, 3, 4]) # matrix is a specialised array of 2 dimension

matrix([[1, 2, 3, 4]])

In [53]:
mat = np.matrix([1, 2, 3, 4])

In [55]:
type(mat)

numpy.matrix

In [57]:
mat.ndim

2

In [59]:
# to understand the dimention, see the no of opening/closing square bracket

In [61]:
np.matrix([[[1,2],[3,4],[5,6]]])  # will throw error - matrix must be 2-dimensional

ValueError: matrix must be 2-dimensional

In [63]:
arr3 = np.array([[[1,2],[3,4],[5,6]]])

In [65]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [69]:
# more way to array
l = [1, 2, 3]
np.asarray(l)  # initial function asarray to convert to an array, np.array came after this

array([1, 2, 3])

In [71]:
np.asanyarray([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# asanyarray will convert the input to an adarry, but if something as already in array it will not convert >> it will pass ndarray subclass throuth
# if somthingis already an array or part of array, it will simply allow to pass throuth it

In [75]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [77]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [79]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [81]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
for i in arr:
    print(i)

1
2
3
4
5


In [85]:
arr[0]

1

In [87]:
arr[3]

4

In [89]:
#array is mutable
arr[0] = 100

In [91]:
arr

array([100,   2,   3,   4,   5])

In [93]:
a = arr  # a and arr will point to same memory location, so if there is changes in a or both it will reflact in both

In [95]:
a

array([100,   2,   3,   4,   5])

In [97]:
arr

array([100,   2,   3,   4,   5])

In [99]:
# shallow copy >> change in one array will lead to chnage in another

In [101]:
a[1] = 200

In [103]:
a

array([100, 200,   3,   4,   5])

In [105]:
arr

array([100, 200,   3,   4,   5])

In [117]:
b = arr.copy() # deep copy >> change in one array will not replect in another

In [109]:
b

array([100, 200,   3,   4,   5])

In [111]:
b[2] = 3000

In [113]:
b

array([ 100,  200, 3000,    4,    5])

In [115]:
arr

array([100, 200,   3,   4,   5])

In [119]:
# to creae an array >> np.array, np.array, np.asanyarray

In [121]:
# multiple approches to generate any array

In [133]:
arr2 = np.fromfunction(lambda i, j: i==j, (3,3)) # construct an array by executing a function over each coorinate

In [135]:
arr2

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [137]:
arr2.ndim

2

In [141]:
arr2.shape # shape of array

(3, 3)

In [143]:
arr2.size  # no of element in array

9

In [145]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [149]:
for i in range(5):
    print(i)

0
1
2
3
4


In [153]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [157]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [167]:
iterator = (i for i in range(5))

In [169]:
iterator

<generator object <genexpr> at 0x0000023B026437C0>

In [171]:
# np.formiter(iterator, int)  # create a new 1- dimentional array from an iterable object

In [173]:
np.fromstring('22 23 24', sep = " ")

array([22., 23., 24.])

In [180]:
# np.fromstring('22 23 24', sep = " ", dttype = int)

In [182]:
# for string character you have to use splite
string = "Lucky, Kushik, LalBabu"
string.split(" , ")

['Lucky, Kushik, LalBabu']

In [184]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#other method of numpy >> to generate a sequence of number
np.arange