NUMPY ASSIGNMENT

In [2]:
import numpy as np

In [4]:
# 1. Create a 3x3 NumPy Array with Random Integers and Interchange Rows and Columns

arr = np.random.randint(1, 101, size=(3, 3))

transposed_arr = arr.T

print("Original Array:\n", arr)
print("Transposed Array:\n", transposed_arr)


Original Array:
 [[ 1  9  7]
 [61 86 69]
 [18 57 74]]
Transposed Array:
 [[ 1 61 18]
 [ 9 86 57]
 [ 7 69 74]]


In [6]:
# 2. Generate a 1D NumPy Array and Reshape
arr = np.arange(10)

# Reshape to 2x5 array
reshaped_2x5 = arr.reshape(2, 5)

# Reshape to 5x2 array
reshaped_5x2 = arr.reshape(5, 2)

print("1D Array:", arr)
print("2x5 Array:\n", reshaped_2x5)
print("5x2 Array:\n", reshaped_5x2)


1D Array: [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [8]:
# 3. Create a 4x4 NumPy Array with Random Float Values and Add Border of Zeros
arr = np.random.rand(4, 4)

arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:\n", arr)
print("6x6 Array with Border of Zeros:\n", arr_with_border)


Original 4x4 Array:
 [[0.0870261  0.13813807 0.46225059 0.17865876]
 [0.22879994 0.00143281 0.45830933 0.61207673]
 [0.16107182 0.39681009 0.16462708 0.44694311]
 [0.62646458 0.6273652  0.72482306 0.74497547]]
6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.0870261  0.13813807 0.46225059 0.17865876 0.        ]
 [0.         0.22879994 0.00143281 0.45830933 0.61207673 0.        ]
 [0.         0.16107182 0.39681009 0.16462708 0.44694311 0.        ]
 [0.         0.62646458 0.6273652  0.72482306 0.74497547 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [10]:
# 4. Create an Array of Integers from 10 to 60 with a Step of 5
arr = np.arange(10, 65, 5)

print("Array:", arr)


Array: [10 15 20 25 30 35 40 45 50 55 60]


In [12]:
# 5. Create a NumPy Array of Strings and Apply Case Transformations
arr = np.array(['python', 'numpy', 'pandas'])

upper_case = np.char.upper(arr)
lower_case = np.char.lower(arr)
title_case = np.char.title(arr)

print("Original Array:", arr)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [14]:
# 6. Generate a NumPy Array of Words and Insert Spaces Between Characters
arr = np.array(['hello', 'world', 'numpy'])

spaced_arr = np.char.join(' ', arr)

print("Original Array:", arr)
print("Array with Spaces Between Characters:", spaced_arr)


Original Array: ['hello' 'world' 'numpy']
Array with Spaces Between Characters: ['h e l l o' 'w o r l d' 'n u m p y']


In [16]:
# 7. Perform Element-wise Operations on Two 2D NumPy Arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
# 8. Create a 5x5 Identity Matrix and Extract Diagonal Elements
identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [20]:
# 9. Find All Prime Numbers in a NumPy Array of 100 Random Integers
arr = np.random.randint(0, 1001, 100)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = arr[np.vectorize(is_prime)(arr)]

print("Array:", arr)
print("Prime Numbers:", prime_numbers)


Array: [102 328 575 375 762 345 653 620 904 121  84 163 832 168 101 817 878 292
 412 476 805 453 701 634 893  25 728 222 436   2 200 371 386  24  78 563
 681 804 150  60 131 833 624  21 915  70 543 207 368 141 468 224 547 135
 514 439 403 592 272 790 141 133 994 878 256 576 222 840 525 165 971 531
 328 750 758 890 118 314  16 854 655 140 653 435 850  16 931 401 871  83
 238 408 724 189 250 510 763 436 701 406]
Prime Numbers: [653 163 101 701   2 563 131 547 439 971 653 401  83 701]


In [22]:
# 10. Calculate Weekly Averages of Daily Temperatures for a Month
temperatures = np.random.randint(15, 35, size=30)

weekly_averages = [np.mean(temperatures[i:i+7]) for i in range(0, len(temperatures), 7)]

print("Daily Temperatures:", temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures: [19 26 27 21 23 16 19 33 29 31 18 23 34 17 24 20 33 16 18 26 33 19 31 24
 32 31 26 24 27 19]
Weekly Averages: [21.571428571428573, 26.428571428571427, 24.285714285714285, 26.714285714285715, 23.0]
